#pragma once

// Declare an event base
ESP_EVENT_DECLARE_BASE(TIMER_EVENTS); 
ESP_EVENT_DECLARE_BASE(PUBLICATION_EVENTS);

enum EVENT_TIMER_TYPES {
    EVENT_TIMER_STARTED,
    EVENT_TIMER_EXPIRY,
    EVENT_TIMER_STOPPED
};

enum EVENT_PUBLICATION_TYPE {
    EVENT_PUBLICATION_TEMPC,
    EVENT_PUBLICATION_HUMIDITY,
};

